apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  group: hanzo.ai
resources:
  - hanzo.ai_canaryconfigs.yaml
  - hanzo.ai_environments.yaml
  - hanzo.ai_functions.yaml
  - hanzo.ai_httptriggers.yaml
  - hanzo.ai_kuberneteswatchtriggers.yaml
  - hanzo.ai_messagequeuetriggers.yaml
  - hanzo.ai_packages.yaml
  - hanzo.ai_timetriggers.yaml
